# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        private_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/var/uploads'
    filesystems:
        private_uploads_filesystem:
            adapter: private_uploads_adapter

